import React from 'react';
import {
  BlockOutlined,
  CompassOutlined,
  DashboardOutlined,
  FormOutlined,
  HomeOutlined,
  LayoutOutlined,
  LineChartOutlined,
  TableOutlined,
  UserOutlined,
} from '@ant-design/icons';
import { ReactComponent as NftIcon } from '@app/assets/icons/nft-icon.svg';

export interface SidebarNavigationItem {
  title: string;
  key: string;
  url?: string;
  children?: SidebarNavigationItem[];
  icon?: React.ReactNode;
  old_template: boolean;
  role: string;
}

export const sidebarNavigation: SidebarNavigationItem[] = [
  {
    title: 'common.nft-dashboard',
    key: 'nft-dashboard',
    // TODO use path variable
    url: '/',
    icon: <NftIcon />,
    old_template: true,
    role: 'default',
  },
  {
    title: 'common.medical-dashboard',
    key: 'medical-dashboard',
    url: '/medical-dashboard',
    icon: <DashboardOutlined />,
    old_template: true,
    role: 'default',
  },
  {
    title: 'iot.iot-edu-nav-title',
    key: 'iot.iot-edu-nav-title',
    icon: <HomeOutlined />,
    old_template: false,
    role: 'default',
    children: [
      {
        title: 'iot.list-courses-nav-title',
        key: 'iot.list-courses-nav-title',
        url: '/iot-edu/list-courses',
        old_template: false,
        role: 'teacher|student',
      },
      {
        title: 'Очередь выполнения',
        key: 'Очередь выполнения',
        url: '/iot-edu/stands-queue',
        old_template: false,
        role: 'teacher|student',
      },
      {
        title: 'Список групп',
        key: 'Список групп',
        url: '/iot-edu/list-groups',
        old_template: false,
        role: 'admin',
      },
      {
        title: 'Список пользователей',
        key: 'Список пользователей',
        url: '/iot-edu/list-users',
        old_template: false,
        role: 'admin',
      },
      // {
      //   // todo translate
      //   title: 'Информация о группе',
      //   key: 'detail-group',
      //   url: '/iot-edu/detail-group',
      //   old_template: false,
      // },
      // {
      //   // todo translate
      //   title: 'Преподаватели',
      //   key: 'list-teachers',
      //   url: '/iot-edu/list-teachers',
      //   old_template: false,
      // },
      // {
      //   // todo translate
      //   title: 'Список заданий',
      //   key: 'calendar-tasks',
      //   url: '/iot-edu/calendar-tasks',
      //   old_template: false,
      // },
      // {
      //   // todo translate
      //   title: 'Добавить группу',
      //   key: 'add-group',
      //   url: '/iot-edu/add-group',
      //   old_template: false,
      // },
      // {
      //   // todo translate
      //   title: 'Информация о курсе',
      //   key: 'detail-course',
      //   url: '/iot-edu/detail-course',
      //   old_template: false,
      // },
      // {
      //   title: 'iot.list-groups-nav-title',
      //   key: 'iot.list-groups-nav-title',
      //   url: '/iot-edu/list-groups',
      //   old_template: false,
      // },
      // {
      //   title: 'iot.add-course-form-nav-title',
      //   key: 'iot.add-course-form-nav-title',
      //   url: '/iot-edu/list-courses/add',
      //   old_template: false,
      // },
      // {
      //   title: 'iot.list-users-nav-title',
      //   key: 'iot.list-users-nav-title',
      //   url: '/iot-edu/list-users',
      //   old_template: false,
      // },
    ],
  },
  {
    title: 'common.apps',
    key: 'apps',
    icon: <HomeOutlined />,
    old_template: true,
    role: 'default',
    children: [
      {
        title: 'common.feed',
        key: 'feed',
        url: '/apps/feed',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.kanban',
        key: 'kanban',
        url: '/apps/kanban',
        old_template: true,
        role: 'default',
      },
    ],
  },
  {
    title: 'common.authPages',
    key: 'auth',
    icon: <UserOutlined />,
    old_template: true,
    role: 'default',
    children: [
      {
        title: 'common.login',
        key: 'login',
        url: '/auth/login',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.signUp',
        key: 'singUp',
        url: '/auth/sign-up',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.lock',
        key: 'lock',
        url: '/auth/lock',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.forgotPass',
        key: 'forgotPass',
        url: '/auth/forgot-password',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.securityCode',
        key: 'securityCode',
        url: '/auth/security-code',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.newPassword',
        key: 'newPass',
        url: '/auth/new-password',
        old_template: true,
        role: 'default',
      },
    ],
  },
  {
    title: 'common.forms',
    key: 'forms',
    icon: <FormOutlined />,
    old_template: true,
    role: 'default',
    children: [
      {
        title: 'common.advancedForms',
        key: 'advanced-forms',
        url: '/forms/advanced-forms',
        old_template: true,
        role: 'default',
      },
    ],
  },
  {
    title: 'common.dataTables',
    key: 'dataTables',
    url: '/data-tables',
    icon: <TableOutlined />,
    old_template: true,
    role: 'default',
  },
  {
    title: 'common.charts',
    key: 'charts',
    url: '/charts',
    icon: <LineChartOutlined />,
    old_template: true,
    role: 'default',
  },
  {
    title: 'common.maps',
    key: 'maps',
    icon: <CompassOutlined />,
    old_template: true,
    role: 'default',
    children: [
      {
        title: 'common.googleMap',
        key: 'google-maps',
        url: '/maps/google-maps',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.leafletMap',
        key: 'leaflet-maps',
        url: '/maps/leaflet-maps',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.reactSimpleMaps',
        key: 'react-simple-maps',
        url: '/maps/react-simple-maps',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.pigeonMaps',
        key: 'pigeon-maps',
        url: '/maps/pigeon-maps',
        old_template: true,
        role: 'default',
      },
    ],
  },
  {
    title: 'common.pages',
    key: 'pages',
    icon: <LayoutOutlined />,
    old_template: true,
    role: 'default',
    children: [
      {
        title: 'common.profilePage',
        key: 'profile',
        url: '/profile',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.serverError',
        key: 'serverError',
        url: '/server-error',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.clientError',
        key: '404Error',
        url: '/404',
        old_template: true,
        role: 'default',
      },
    ],
  },
  {
    title: 'common.ui',
    key: 'ui',
    icon: <BlockOutlined />,
    old_template: true,
    role: 'default',
    children: [
      {
        title: 'common.alert',
        key: 'alert',
        url: '/ui-components/alert',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.avatar',
        key: 'avatar',
        url: '/ui-components/avatar',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.autocomplete',
        key: 'auto-complete',
        url: '/ui-components/auto-complete',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.badge',
        key: 'badge',
        url: '/ui-components/badge',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.breadcrumbs',
        key: 'breadcrumbs',
        url: '/ui-components/breadcrumbs',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.button',
        key: 'button',
        url: '/ui-components/button',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.checkbox',
        key: 'checkbox',
        url: '/ui-components/checkbox',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.collapse',
        key: 'collapse',
        url: '/ui-components/collapse',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.dateTimePicker',
        key: 'dateTimePicker',
        url: '/ui-components/date-time-picker',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.dropdown',
        key: 'dropdown',
        url: '/ui-components/dropdown',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.input',
        key: 'input',
        url: '/ui-components/input',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.modal',
        key: 'modal',
        url: '/ui-components/modal',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.notification',
        key: 'notification',
        url: '/ui-components/notification',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.pagination',
        key: 'pagination',
        url: '/ui-components/pagination',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.popconfirm',
        key: 'popconfirm',
        url: '/ui-components/popconfirm',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.popover',
        key: 'popover',
        url: '/ui-components/popover',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.progress',
        key: 'progress',
        url: '/ui-components/progress',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.radio',
        key: 'radio',
        url: '/ui-components/radio',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.rate',
        key: 'rate',
        url: '/ui-components/rate',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.result',
        key: 'result',
        url: '/ui-components/result',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.select',
        key: 'select',
        url: '/ui-components/select',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.skeleton',
        key: 'skeleton',
        url: '/ui-components/skeleton',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.spinner',
        key: 'spinner',
        url: '/ui-components/spinner',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.steps',
        key: 'steps',
        url: '/ui-components/steps',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.switch',
        key: 'switch',
        url: '/ui-components/switch',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.tabs',
        key: 'tabs',
        url: '/ui-components/tabs',
        old_template: true,
        role: 'default',
      },
      {
        title: 'common.upload',
        key: 'upload',
        url: '/ui-components/upload',
        old_template: true,
        role: 'default',
      },
    ],
  },
];
